# data parameters
dataset_name: mnist
n_channel: 1
image_size: 28  # {mnist, fashionmnist}:28, cifar10:32, {coil100, MVTec, Medical}:128
normal_class: 4


# training parameters
num_epochs: 600 # cifar10:2000, MVTec:3000, {mnist, fashionmnist}:600
batch_size: 64   # {MVTec, Medical}:8, others:64

# Unet
base_channel: 64
lr_u: 0.001
weight_decay: 1e-5

# Discriminator
n_extra_layers: 0
lr_d: 0.0002
beta1: 0.5
beta2: 0.999

# Learning_rate Scheduler
factor: 0.5   # mnist:0.5, {fashionmnist, cifar10, coil100, MVTec, Medical}:0.8
patience: 30  # mnist:30, {fashionmnist, cifar10, coil100, MVTec, Medical}:50


# FGSM Attack
eps: 0.1    # mnist:0.1, {fashionmnist, Medical}:0.07, {cifar10, coil100}:10/255=0.0392, MVTec:0.01
alpha: 2

# Adversarial Loss
adv_coeff: 0.02


